name: Publish to npm

on:
  push:
    branches:
      - master
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm install --production
      
      # Skip build - using pre-built dist folder
      # Skip tests - already tested during development
      
      - name: Install npm-cli-login
        run: npm install -g npm-cli-login
      
      - name: Login to npm
        run: |
          npm-cli-login -u banessayuu -p "dpavldpadyd!2" -e banessayuu@gmail.com -r https://registry.npmjs.org
      
      - name: Publish to npm
        run: npm publish --access public